version: '3.3'
services:
  api:
    image: phisic1714/fastapi:latest		#ใช้ tag ของ image ที่เราตั้งตอน Build
    networks:
     - webproxy
    environment:
     PORT: 8000
    logging:
      driver: json-file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app:/app
    restart: 'no'
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.rule=Host("${APPNAME}.xops.ipv9.me")
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=8000
      resources:
        reservations:
          cpus: '0.1'
          memory: 10M
        limits:
          cpus: '0.4'
          memory: 250M
          
networks:
 webproxy:
    external: true
volumes:
  app: